Repository PorkchopDonut/bug-tracker, pull requests merged in 2020-03, with the labels that each got.

#30 Issue-16 Delete employee and customer issues Joe
  src/main/TerminalX.java
  src/resources/forms/CustomerIssueDetailsForm.form
  src/resources/forms/CustomerIssueDetailsForm.java
  src/resources/forms/EmployeeIssueDetailsForm.java
Labels: enhancement

#37 Issue-26 - Refactored Issue Details generation to use enum names - Logan
  issues.json
  src/resources/forms/CustomerIssueDetailsForm.java
  src/resources/forms/EmployeeIssueDetailsForm.java
Labels: bug

#40 Demo - Changed Low priority to Medium - Logan
  issues.json
Labels: documentation

#41 Issue 25 - Added ability to update issue details from employee menu - Logan & Kris
  bug-tracker.iml
  issues.json
  src/main/Issue.java
  src/main/TerminalX.java
  src/resources/forms/EmployeeIssueDetailsForm.form
  src/resources/forms/EmployeeIssueDetailsForm.java
Labels: enhancement

#42 Issue-38 - Minor refactoring and logic for updated date changes - Log…
  issues.json
  src/main/TerminalX.java
  src/resources/forms/CustomerIssueDetailsForm.java
  src/resources/forms/EmployeeIssueDetailsForm.java
Labels: bug

#44 Issue 16
  issues.json
  src/resources/forms/MenuForm.java
  src/resources/forms/SubmitIssueForm.form
  src/resources/forms/SubmitIssueForm.java
Labels: enhancement

#43 Issue-29 - Added function to prettify UUIDs - Logan, Kris, & Joseph
  src/main/TerminalX.java
  src/resources/forms/CustomerIssueDetailsForm.java
  src/resources/forms/EmployeeIssueDetailsForm.java
Labels: enhancement

#45 Issue-28 - Humanized date values and added double-click support - Log…
  issues.json
  src/main/TerminalX.java
  src/resources/forms/CustomerIssueDetailsForm.java
  src/resources/forms/EmployeeIssueDetailsForm.java
  src/resources/forms/MenuForm.java
Labels: enhancement

#46 Issue-35 - Added error message for invalid issue submissions - Logan …
  src/resources/forms/SubmitIssueForm.form
  src/resources/forms/SubmitIssueForm.java
Labels: enhancement

#47 Issue-32 - Added sorting functionality - Logan & Kris
  src/main/TerminalX.java
  src/resources/forms/MenuForm.form
  src/resources/forms/MenuForm.java
Labels: enhancement

#48 Issue-33 - Added support for filtering archived issues - Logan & Kris
  src/main/TerminalX.java
  src/resources/forms/MenuForm.form
  src/resources/forms/MenuForm.java
Labels: enhancement
